/* Englische Fassung für den CrazyGames-Export.

   Die Quellen bleiben deutsch; tools/crazygames/uebersetzen.js ersetzt
   beim Build jede Zeichenkette, die hier als Schlüssel steht, durch
   ihren Wert. Schlüssel ist der Wert der Zeichenkette, nicht ihr
   Quelltext — "\n" steht also als echter Zeilenumbruch da.

   Kommt im Spiel ein neuer Text dazu, bricht der Build ab und nennt ihn.
   Dann gehört er hierher oder, falls er gar kein Text ist, nach `code`. */

module.exports = {

  texte: {
    /* ---- Bauten ---- */
    'Pylon': 'Pylon',
    'Reaktor': 'Reactor',
    'Akku': 'Battery',
    'Blaster': 'Blaster',
    'Kanone': 'Cannon',
    'Frostturm': 'Frost Tower',
    'Barriere': 'Barrier',
    'Lichtbogen': 'Arc Tower',
    'Minenleger': 'Minelayer',
    'Werkdrohne': 'Repair Drone',
    'Schildfeld': 'Shield Field',
    'Pylone': 'Pylons',
    'Reaktoren': 'Reactors',
    'Akkus': 'Batteries',
    'Kanonen': 'Cannons',
    'Frosttürme': 'Frost Towers',
    'Barrieren': 'Barriers',

    'Trägt das Energienetz weiter nach außen.': 'Carries the power grid further out.',
    '+6 Energie/s und entlastet den eigenen Netzast.': '+6 energy/s and relieves its own grid branch.',
    '+52 Speicher, trägt seinen Knoten mit.': '+52 storage, helps carry its node.',
    'Feuert schnell und dauerhaft, und er ist billig.': 'Fires fast and steadily, and it is cheap.',
    'Schießt langsam, trifft dafür eine ganze Fläche.': 'Fires slowly, but hits a whole area.',
    'Bremst Gegner um 50 %.': 'Slows enemies by 50%.',
    'Lenkt Bodentruppen um und braucht keinen Strom. Mit gedrückter Maustaste entsteht eine ganze Reihe.':
      'Diverts ground units and needs no power. Hold the mouse button to build a whole row.',
    'Der Bogen springt auf bis zu drei weitere Gegner über, jeder Sprung schwächer.':
      'The arc jumps to up to three more enemies, each jump weaker.',
    'Legt Minen in unbewachte Zellen; sie zünden unter Bodentruppen.':
      'Lays mines in unguarded tiles; they go off under ground units.',
    'Setzt beschädigte Bauten in Reichweite instand, 14 Struktur je Sekunde.':
      'Repairs damaged buildings in range, 14 structure per second.',
    'Lädt aus überschüssiger Energie vor und fängt damit im Gefecht 70 % jedes Treffers auf Nachbarbauten ab.':
      'Charges up from surplus energy and absorbs 70% of every hit on nearby buildings in combat.',

    /* ---- Stufe-5-Fähigkeiten ---- */
    'Zwillingssalve': 'Twin Salvo',
    'Feuert gleichzeitig auf ein zweites Ziel': 'Fires at a second target at the same time',
    'Brandsatz': 'Incendiary',
    'Der Einschlag setzt Getroffene in Brand': 'Impacts set targets on fire',
    'Vereisung': 'Deep Freeze',
    'Friert gebremste Gegner kurz völlig ein': 'Briefly freezes slowed enemies solid',
    'Verstärkerfeld': 'Amplifier Field',
    'Türme im Netzradius schlagen 15 % härter': 'Towers in its grid radius hit 15% harder',
    'Materiekonverter': 'Matter Converter',
    'Erzeugt zusätzlich 0,6 Materie je Sekunde': 'Also produces 0.6 matter per second',
    'Spitzenlast': 'Peak Load',
    'Fällt der Puffer unter 15 %, speist der Akku einmal je Welle seinen ganzen Speicher ein':
      'When the buffer drops below 15%, the battery feeds in its full storage once per wave',
    'Reaktivpanzerung': 'Reactive Armor',
    'Reißt beim Bersten die Angreifer mit': 'Takes its attackers with it when it bursts',
    'Kettenreaktion': 'Chain Reaction',
    'Wer am Bogen stirbt, reißt seine Nachbarn mit': 'Enemies killed by the arc take their neighbors with them',
    'Näherungszünder': 'Proximity Fuse',
    'Die Minen zünden auch unter fliegenden Gegnern': 'Mines also go off under flying enemies',
    'Notfallschweißung': 'Emergency Weld',
    'Fällt ein Bau unter ein Viertel Struktur, setzt die Drohne ihn einmal je Welle sofort ganz instand':
      'When a building drops below a quarter of its structure, the drone fully repairs it once per wave',
    'Rückkopplung': 'Feedback',
    'Zwei Fünftel des geschluckten Schadens treffen den Angreifer': 'Two fifths of the absorbed damage hits the attacker',

    /* ---- Gegner ---- */
    'Crawler': 'Crawler',
    'Runner': 'Runner',
    'Brute': 'Brute',
    'Drohne': 'Drone',
    'Mender': 'Mender',
    'Saboteur': 'Saboteur',
    'Splitter': 'Splitter',
    'Larve': 'Larva',
    'Zapfer': 'Drainer',
    'Wächter': 'Warden',
    'Titan': 'Titan',
    'Moloch': 'Moloch',
    'Nexus': 'Nexus',
    'Schwer gepanzert und heilt sich selbst': 'Heavily armored and heals itself',
    'Unverwundbar, solange seine Wächter stehen': 'Invulnerable while its Wardens stand',
    'Zapft deinen Puffer an und wirft ständig Brut aus': 'Drains your buffer and keeps spawning brood',
    'Panzer ': 'armor ',
    'Schild': 'Shield',
    'fliegt': 'flies',
    'kaum bremsbar': 'hard to slow',
    'heilt': 'heals',
    'regeneriert': 'regenerates',
    'jagt Pylone': 'hunts pylons',
    'teilt sich': 'splits',
    'zapft Energie': 'drains energy',
    'schildet ab': 'shields others',
    'wirft Brut aus': 'spawns brood',

    /* ---- Last- und Zielpriorität ---- */
    'Vorrang': 'High',
    'Normal': 'Normal',
    'Sparlast': 'Low',
    'Kernnächster': 'Closest to core',
    'Wer dem Kern am nächsten ist': 'Whoever is closest to the core',
    'Nächster': 'Nearest',
    'Wer dem Turm am nächsten ist': 'Whoever is closest to the tower',
    'Stärkster': 'Strongest',
    'Wer die meiste Struktur übrig hat': 'Whoever has the most structure left',
    'Schnellster': 'Fastest',
    'Wer gerade am schnellsten läuft': 'Whoever is moving fastest right now',

    /* ---- Kernmodi ---- */
    'Einspeisung': 'Supply',
    'Speicher': 'Storage',
    '+25 % Nachschub\n−15 % Speicher': '+25% regen\n−15% storage',
    '+25 % Regeneration, dafür 15 % weniger Speicher': '+25% regeneration, but 15% less storage',
    '+40 % Speicher\n−15 % Nachschub': '+40% storage\n−15% regen',
    '+40 % Speicher, dafür 15 % weniger Regeneration': '+40% storage, but 15% less regeneration',
    '60 % Kernschaden\naus dem Puffer': '60% of core damage\nfrom the buffer',
    '60 % des Kernschadens zahlt der Puffer — 2,2 Energie je Schadenspunkt, aber nie unter 35 % Ladung, dafür 10 % weniger Nachschub und Speicher':
      'The buffer pays for 60% of core damage — 2.2 energy per damage point, but never below 35% charge; costs 10% regen and storage',

    /* ---- Kernbefehle ---- */
    'Entladung': 'Discharge',
    'Wirft den halben Puffer als Druckwelle nach außen. Schaden wächst mit der Ladung.':
      'Releases half the buffer as an outward shockwave. Damage grows with the charge.',
    'Netzstoß': 'Grid Surge',
    '6 s doppelter Schaden bei knapp halbem Verbrauch — danach ist der Puffer leer.':
      '6 s of double damage at just under half the energy cost — the buffer is empty afterwards.',
    'Notpuls': 'Repair Pulse',
    'Setzt jeden Bau im Netz um ein Drittel instand, ohne Materie.':
      'Repairs every building on the grid by a third, free of matter.',

    /* ---- Sturmwellen ---- */
    'Störnebel': 'Jamming Fog',
    'Alle Türme reichen 25 % weniger weit': 'All towers have 25% less range',
    'EMP-Front': 'EMP Front',
    'Der Puffer lädt kaum noch nach': 'The buffer barely recharges',
    'Magnetsturm': 'Magnetic Storm',
    'Geschosse fliegen 40 % langsamer': 'Projectiles fly 40% slower',
    'Schwarm': 'Swarm',
    'Es kommen weit mehr Gegner, dafür dünnhäutige': 'Far more enemies, but thin-skinned ones',
    'Kältefest': 'Frostproof',
    'Gegner lassen sich nicht bremsen': 'Enemies cannot be slowed',
    'Panzerkonvoi': 'Armored Convoy',
    'Jeder Gegner trägt 4 Panzerung mehr': 'Every enemy has 4 more armor',
    'Hetzjagd': 'Stampede',
    'Gegner laufen 30 % schneller': 'Enemies move 30% faster',

    /* ---- Karten ---- */
    'Fokussierte Optik': 'Focused Optics',
    '+14 % Reichweite für alle Türme': '+14% range for all towers',
    'Verdichtete Ladung': 'Dense Charge',
    '+18 % Schaden': '+18% damage',
    'Kürzere Zyklen': 'Shorter Cycles',
    '+16 % Feuerrate': '+16% fire rate',
    'Supraleiter': 'Superconductor',
    'Jeder Schuss kostet 18 % weniger Energie': 'Every shot costs 18% less energy',
    'Größerer Puffer': 'Bigger Buffer',
    '+55 Energiespeicher': '+55 energy storage',
    'Heißer Reaktorkern': 'Hot Reactor Core',
    '+5 Energie pro Sekunde': '+5 energy per second',
    'Kernkühlung': 'Core Cooling',
    '+25 % Energie-Regeneration': '+25% energy regeneration',
    'Netzausbau': 'Grid Expansion',
    'Kern und Pylone reichen 0,7 Zellen weiter': 'Core and pylons reach 0.7 tiles further',
    'Bergungstrupp': 'Salvage Crew',
    '+30 % Materie aus Abschüssen': '+30% matter from kills',
    'Werkbank': 'Workbench',
    'Alle Bauteile kosten 12 % weniger': 'All buildings cost 12% less',
    'Panzerplatten': 'Armor Plating',
    '+30 % Struktur für alle Bauten': '+30% structure for all buildings',
    'Nanoreparatur': 'Nano Repair',
    'Bauten heilen 2 Struktur pro Sekunde': 'Buildings heal 2 structure per second',
    'Nachschublieferung': 'Supply Drop',
    '+25 Materie nach jeder Welle': '+25 matter after every wave',
    'Kernwerft': 'Core Shipyard',
    'Der Kern setzt sich nach jeder Welle um 70 Struktur instand': 'The core repairs 70 structure after every wave',
    'Schnellwechsel': 'Quick Swap',
    'Blaster: +45 % Feuerrate': 'Blaster: +45% fire rate',
    'Gehärtete Kerne': 'Hardened Cores',
    'Blaster: +45 % Schaden': 'Blaster: +45% damage',
    'Doppelrohr': 'Double Barrel',
    'Blaster: 40 % weniger Energie je Schuss': 'Blaster: 40% less energy per shot',
    'Streuladung': 'Scatter Charge',
    'Kanonen und Minen: +45 % Wirkungsradius': 'Cannons and mines: +45% blast radius',
    'Schwere Rohre': 'Heavy Barrels',
    'Kanonen: +50 % Schaden': 'Cannons: +50% damage',
    'Autolader': 'Autoloader',
    'Kanonen: +40 % Feuerrate': 'Cannons: +40% fire rate',
    'Langrohr': 'Long Barrel',
    'Kanonen: +30 % Reichweite': 'Cannons: +30% range',
    'Frostbrand': 'Frostbite',
    'Frost bremst stärker und länger': 'Frost slows harder and longer',
    'Kältestrahl': 'Cold Beam',
    'Frost: +120 % Schaden': 'Frost: +120% damage',
    'Weitwurf': 'Long Throw',
    'Frost: +40 % Reichweite': 'Frost: +40% range',
    'Überschlag': 'Flashover',
    'Lichtbogen: ein Sprung mehr': 'Arc Tower: one more jump',
    'Ionenspur': 'Ion Trail',
    'Lichtbogen: +45 % Schaden': 'Arc Tower: +45% damage',
    'Minenfeld': 'Minefield',
    'Jeder Minenleger hält zwei Minen mehr bereit': 'Every minelayer keeps two more mines ready',
    'Wartungsnetz': 'Maintenance Net',
    'Werkdrohnen setzen 60 % schneller instand': 'Repair drones repair 60% faster',
    'Feldharmonie': 'Field Harmony',
    'Schildfelder schlucken 15 Prozentpunkte mehr, höchstens 90 %': 'Shield fields absorb 15 percentage points more, up to 90%',
    'Durchschlagmunition': 'Piercing Rounds',
    'Jeder Treffer ignoriert 5 Panzerung': 'Every hit ignores 5 armor',
    'Flakmunition': 'Flak Rounds',
    '+60 % Schaden gegen fliegende Ziele': '+60% damage against flying targets',
    'Unterkühlung': 'Hypothermia',
    'Jeder Treffer bremst kurz um 10 %': 'Every hit briefly slows by 10%',
    'Sprengbolzen': 'Explosive Bolts',
    'Getötete Gegner reißen Umstehende mit': 'Killed enemies take bystanders with them',
    'Kettenblitz': 'Chain Lightning',
    'Geschosse springen mit halber Wucht auf ein zweites Ziel über': 'Projectiles jump to a second target at half force',
    'Dornenbarrieren': 'Thorn Barriers',
    'Barrieren verletzen ihre Angreifer': 'Barriers hurt their attackers',
    'Kernstoß': 'Core Shock',
    'Der Kern verletzt und stößt zurück, was ihn angreift': 'The core hurts and knocks back whatever attacks it',
    'Inselbetrieb': 'Island Mode',
    'Türme ohne Netzanschluss feuern mit halber Rate statt gar nicht': 'Towers without a grid connection fire at half rate instead of not at all',
    'Kaltstart': 'Cold Start',
    'Zu Beginn jeder Welle ist der Puffer voll': 'The buffer is full at the start of every wave',
    'Ausschlachten': 'Scrapping',
    'Abbau erstattet den vollen Preis': 'Selling refunds the full price',
    'Zündschnur': 'Short Fuse',
    '+38 % Schaden, aber 18 % weniger Struktur': '+38% damage, but 18% less structure',
    'Hochlast': 'High Load',
    '+32 % Feuerrate, aber +25 % Energieverbrauch': '+32% fire rate, but +25% energy use',
    'Schlanke Bauweise': 'Lean Build',
    '28 % billiger bauen, 14 % weniger Struktur': 'Build 28% cheaper, 14% less structure',
    'Fernzündung': 'Remote Detonation',
    '+32 % Reichweite, aber 8 % weniger Schaden': '+32% range, but 8% less damage',
    'Notstromkreis': 'Emergency Circuit',
    '+8 Energie pro Sekunde, aber 30 Speicher weniger': '+8 energy per second, but 30 less storage',
    'Kernanzapfung': 'Core Tap',
    '+55 % Materie, aber der Kern verliert 70 Struktur': '+55% matter, but the core loses 70 structure',
    'Brennstab': 'Fuel Rod',
    '+20 % Schaden, aber Bauten kosten 10 % mehr': '+20% damage, but buildings cost 10% more',
    'Hochspannung': 'High Voltage',
    'Alle Leitungen tragen 35 % mehr Last': 'All lines carry 35% more load',
    'Sammelschiene': 'Busbar',
    '+20 % Leitungslast und 0,4 Zellen mehr Netzradius': '+20% line load and 0.4 tiles more grid radius',
    'Lastverteiler': 'Load Balancer',
    'Reaktoren entlasten ihren Ast doppelt so stark': 'Reactors relieve their branch twice as much',
    'Kondensatorbank': 'Capacitor Bank',
    'Kernbefehle sind 28 % schneller wieder bereit': 'Core commands recharge 28% faster',
    'Schwungrad': 'Flywheel',
    'Kernbefehle ziehen 35 % weniger aus dem Puffer': 'Core commands draw 35% less from the buffer',
    'Zellenstapel': 'Cell Stack',
    'Akkus fassen 45 % mehr': 'Batteries hold 45% more',
    'Schnellschaltung': 'Fast Switch',
    'Der Kern schaltet doppelt so schnell um': 'The core switches modes twice as fast',
    'Notreserve': 'Emergency Reserve',
    'Der Kern bekommt 150 Struktur mehr und steht sofort wieder ganz da': 'The core gains 150 structure and is fully restored at once',
    'Schildbrecher': 'Shieldbreaker',
    'Geschosse wirken voll gegen Schilde': 'Projectiles deal full damage to shields',
    'Überlastventil': 'Overload Valve',
    'Überladung kostet nur noch das Doppelte': 'Overload only costs double',
    'Zweiter Kernring': 'Second Core Ring',
    'Kern und Pylone reichen 1,6 Zellen weiter': 'Core and pylons reach 1.6 tiles further',
    'Fusionszelle': 'Fusion Cell',
    '+10 Energie pro Sekunde und +90 Speicher': '+10 energy per second and +90 storage',
    'Werkstatt': 'Workshop',
    'Jeder bestehende Bau steigt sofort eine Stufe auf': 'Every existing building instantly gains a level',
    'Abschirmung': 'Shielding',
    'Störnebel und EMP-Front wirken nicht mehr gegen dich': 'Jamming Fog and EMP Front no longer affect you',
    'Zwitterkern': 'Hybrid Core',
    'Der Kernmodus verliert die Hälfte seines Nachteils': 'The core mode loses half its drawback',
    'Automatikschaltung': 'Auto Overload',
    'Steht der Puffer über 85 %, feuern alle Türme überladen — ohne Aufpreis':
      'While the buffer is above 85%, all towers fire overloaded — at no extra cost',

    /* ---- Himmelsrichtungen ---- */
    'Ost': 'East', 'Südost': 'Southeast', 'Süd': 'South', 'Südwest': 'Southwest',
    'West': 'West', 'Nordwest': 'Northwest', 'Nord': 'North', 'Nordost': 'Northeast',

    /* ---- Werte beim Überfahren und im Inspektor ---- */
    'Struktur': 'Structure',
    'Schaden': 'Damage',
    'Schaden je Mine': 'Damage per mine',
    'Legeradius': 'Laying radius',
    'Reichweite': 'Range',
    ' Z': ' tiles',                // Zellen; einbuchstabig, fällt der Prüfung sonst nicht auf
    'Mine alle': 'Mine every',
    'Schuss alle': 'Shot every',
    'Dauerlast': 'Steady draw',
    'Instandsetzung': 'Repair',
    'Schluckt': 'Absorbs',
    'Vorrat': 'Reserve',
    'Ertrag': 'Yield',
    'Trägt mit': 'Carries',
    'Netzradius': 'Grid radius',
    'Leitungslast': 'Line load',
    'Netzdrossel': 'Grid throttle',
    'Maximalstufe': 'Max level',
    'Energie je Mine': 'Energy per mine',
    'Energie/Schuss': 'Energy/shot',
    'Sprünge': 'Jumps',
    'Minen scharf': 'Mines armed',
    'Zielpriorität': 'Target priority',
    'Lastpriorität': 'Load priority',
    'Energie je Struktur': 'Energy per structure',
    'Lädt': 'Charges',
    'Energie je Punkt': 'Energy per point',
    'Lädt ab': 'Draws',
    ' % Puffer': '% of buffer',
    ' %': '%',                     // englisch ohne Leerzeichen vor dem Prozentzeichen
    'Feld': 'Field',
    'ohne Strom': 'unpowered',
    'geladen': 'charged',
    'leer': 'empty',
    'bereit': 'ready',
    'verbraucht': 'used up',
    'Leiterbahn': 'Conduit',
    ' % Last': '% load',
    'Strom': 'Power',
    'verbunden': 'connected',
    'GETRENNT': 'CUT OFF',
    'Stufe ': 'Level ',
    '  Stufe ': '  Level ',
    'Ausgebaut': 'Maxed',
    'Ausbau ': 'Upgrade ',
    'Abbau +': 'Sell +',
    'Feld wählen — Esc bricht ab': 'Pick a tile — Esc cancels',
    'Verschieben ': 'Move ',
    'Instand': 'Intact',
    'Reparieren ': 'Repair ',
    'Stufe 5: ': 'Level 5: ',
    'Ziel': 'Target',
    'Zielpriorität: ': 'Target priority: ',
    'Last': 'Load',
    'Lastpriorität: ': 'Load priority: ',
    ' — wer bei knappem Puffer noch feuert  (L)': ' — who keeps firing when the buffer runs low  (L)',
    'Überladung an': 'Overload on',
    'Überladung': 'Overload',
    'Doppelter Schaden, ': 'Double damage, ',
    '-facher Verbrauch (O)': '× energy use (O)',

    /* ---- Meldungen ---- */
    'Unbeschädigt': 'Undamaged',
    'Zu wenig Materie': 'Not enough matter',
    'Alles unbeschädigt': 'Nothing is damaged',
    ' Bau': ' building',
    ' Bauten': ' buildings',
    ' instandgesetzt  −': ' repaired  −',
    ' Materie': ' matter',
    'Trümmer — hier geht nichts': 'Rubble — nothing can go here',
    'Platz belegt': 'Tile occupied',
    'Neues Feld für ': 'Pick a new tile for ',
    ' wählen  −': '  −',
    'Noch nichts gebaut': 'Nothing built yet',
    'Auf welche Seite? Zeiger bewegen, Klick setzt, Esc bricht ab':
      'Which side? Move the pointer, click to place, Esc cancels',
    'Hier ist nichts zu spiegeln': 'Nothing to mirror here',
    'Bauplan gespiegelt: ': 'Blueprint mirrored: ',
    ' GEFALLEN  +150 Materie': ' DEFEATED  +150 matter',
    'Welle ': 'Wave ',
    ' aus ': ' from ',
    'WELLE ': 'WAVE ',
    ' ERSCHEINT': ' APPEARS',
    'Kernmodus: ': 'Core mode: ',
    ' abgewehrt  +': ' repelled  +',
    'Kern ungedeckt — hier fehlt ein Turm': 'Core exposed — no tower covers this side',
    'Spitzenlast — ': 'Peak Load — ',
    ' Energie nachgespeist': ' energy fed in',
    'Notfallschweißung — ': 'Emergency Weld — ',
    ' wieder ganz': ' fully restored',
    'Kern läuft noch an': 'Core is still switching',
    ' s Anlauf': ' s to switch',
    'Kernbefehle wirken nur im Gefecht': 'Core commands only work during combat',
    ' — noch ': ' — ready in ',
    'Puffer zu leer für ': 'Buffer too low for ',
    'Entladung — ': 'Discharge — ',
    ' Schaden im Umkreis': ' damage all around',
    'Netzstoß — ': 'Grid Surge — ',
    ' s doppelter Schaden': ' s of double damage',
    'Notpuls — ': 'Repair Pulse — ',
    ' instandgesetzt': ' repaired',
    ' zielt: ': ' targets: ',
    'Bauplan spiegeln: ': 'Mirror blueprint: ',
    ' für ': ' for ',
    ' weitere sind zu teuer  ·  Klick spiegelt, Esc bricht ab': ' more are too expensive  ·  Click mirrors, Esc cancels',
    'Klick spiegelt, Esc bricht ab': 'Click mirrors, Esc cancels',
    'ohne Netz — feuert nicht': 'no grid — not firing',
    'kein Netz': 'no grid',
    '  (Taste ': '  (key ',
    'Kernbefehl ': 'Core command ',
    ', die Zahl ist der Puffer-Anteil in Energie)': ', the number is its energy cost from the buffer)',
    'Kernmodus ': 'Core mode ',
    '  (Taste K wechselt weiter, ': '  (key K cycles, ',
    ' s Anlauf)': ' s to switch)',
    'Abgeschirmt — erst die Wächter ausschalten': 'Shielded — take out the Wardens first',
    'Rasend': 'Enraged',
    'Kern unter Beschuss — ': 'Core under fire — ',
    ' Gegner ohne Turmdeckung': ' enemies out of tower range',
    'Kern unter Beschuss — kein Turm reicht dorthin': 'Core under fire — no tower reaches there',
    'Sturmwelle: ': 'Storm wave: ',
    'Eine Leitung überlastet — Türme dahinter feuern langsamer': 'One line overloaded — towers behind it fire slower',
    ' Leitungen überlastet — Türme dahinter feuern langsamer': ' lines overloaded — towers behind them fire slower',
    ' Feinde': ' enemies',
    'Bauphase': 'Build phase',
    'Angriff': 'Attack',
    'Weiter': 'Resume',
    'Pause': 'Pause',

    /* ---- Wellenbericht und Kartenwahl ---- */
    'Gegner': 'Enemies',
    'Energie verschossen': 'Energy fired',
    'für Kernbefehle': 'on core commands',
    'Materie': 'Matter',
    'Kernschaden': 'Core damage',
    'Energie als Schild': 'Energy as shield',
    'Bau verloren': 'Building lost',
    'Bauten verloren': 'Buildings lost',
    'Puffer leer': 'Buffer empty',
    'Schaden · ': 'Damage · ',
    ' Stufe ': ' Level ',
    'Druck der nächsten Welle': 'Pressure on the next wave',
    '<span class="have">bereits ${have}×</span>': '<span class="have">owned ${have}×</span>',

    /* ---- Partie, Bestenliste, Tagesfeld ---- */
    'KERN VERLOREN': 'CORE LOST',
    'Du hast ': 'Waves survived: ',          // umgeht „1 waves“
    ' Wellen überstanden.': '.',
    ' Das ist dein bester Lauf.': ' That is your best run.',
    ' Tagesfeld vom ': ' Daily map of ',
    ' — heute spielen alle dieses Feld.': ' — everyone plays this map today.',
    'Ergebnis kopieren': 'Copy result',
    'Ergebnis kopiert': 'Result copied',
    'Tagesfeld ': 'Daily map ',
    'freies Feld': 'free map',
    ' · Welle ': ' · Wave ',
    '" placeholder="dein Name"': '" placeholder="your name"',
    ' aria-label="Name für die Bestenliste" value="': ' aria-label="Name for the leaderboard" value="',
    '<td class="welle">Welle ': '<td class="welle">Wave ',
    'Neu starten': 'Restart',
    'PARTIE GEFUNDEN': 'SAVED RUN FOUND',
    'Du warst nach Welle ': 'You stopped after wave ',
    ' stehengeblieben — ': ' — ',
    ' Bauten, ': ' buildings, ',
    ' Materie. Die angekündigte Welle ': ' matter. The announced wave ',
    ' wartet unverändert.': ' is waiting unchanged.',
    ' Es ist das Tagesfeld vom ': ' It is the daily map of ',
    ' — das bleibt es auch, wenn du an einem anderen Tag weiterspielst.':
      ' — it stays that way if you continue on another day.',
    'Fortsetzen': 'Continue',
    'Neu anfangen': 'Start over',
    'Freies Feld': 'Free map',
    'CORE DEFENSE': 'CORE DEFENSE',
    'Der Kern in der Mitte versorgt deine Türme mit Energie. Angriffe kommen aus allen Richtungen. ':
      'The core in the center powers your towers. Attacks come from every direction. ',
    'Baue Pylone, um das Netz nach außen zu tragen, und Reaktoren, damit dir mitten in der Welle nicht ':
      'Build pylons to carry the grid outward, and reactors so you don\'t run out of ',
    'der Strom ausgeht. Nach jeder Welle wählst du eine Karte, die für den Rest der Partie gilt. ':
      'power mid-wave. After each wave you pick a card that lasts for the rest of the run. ',
    'Auf dem Tagesfeld spielen heute alle dasselbe: dasselbe Gelände, dieselben Wellen, dieselben ':
      'On the daily map everyone plays the same today: same terrain, same waves, same ',
    'Karten zur Wahl. Das freie Feld würfelt jedes Mal neu.':
      'card choices. The free map is rolled anew every time.'
  },

  /* ---- Einführung (einfuehrung.js) ----
     Die Texte sind im Quelltext über mehrere Zeichenketten verteilt;
     jede wird für sich übersetzt, zusammen ergeben sie den Satz. */
  einfuehrung: {
    'Das ist dein Kern. Alles in seinem Leuchten bekommt Strom. ':
      'This is your core. Everything inside its glow gets power. ',
    'Wähle unten den Blaster (Taste 4) und setze ihn neben den Kern.':
      'Pick the Blaster below (key 4) and place it next to the core.',
    'Das Leuchten reicht nicht weit. Ein Pylon (Taste 1) am Rand trägt das Netz ':
      'The glow doesn\'t reach far. A Pylon (key 1) at its edge carries the grid ',
    'weiter nach außen — Türme dahinter bekommen dann auch Strom.':
      'further out — towers beyond it get power too.',
    'Die Pfeile am Spielfeldrand zeigen, woher die Welle kommt. ':
      'The arrows at the edge show where the wave comes from. ',
    'Stell dort noch einen Turm hin und starte sie, wenn du bereit bist.':
      'Put another tower on that side and start it when you are ready.',
    'Jeder Schuss kostet Energie aus dem Puffer, dem blauen Balken oben. ':
      'Every shot costs energy from the buffer, the blue bar at the top. ',
    'Ist er leer, schweigen die Türme — Reaktoren (Taste 2) liefern Nachschub.':
      'When it runs dry, your towers stop firing — Reactors (key 2) refill it faster.',
    'Welle gehalten. Nach jeder Welle wählst du eine Karte, ':
      'Wave held. After every wave you pick a card; ',
    'sie gilt bis zum Ende der Partie.':
      'it lasts until the end of the run.',
    'Ein Klick auf einen Bau zeigt seine Werte. Dort baust du ihn aus, ':
      'Click a building to see its stats. From there you can upgrade, ',
    'reparierst ihn oder baust ihn ab. Viel Erfolg!':
      'repair or sell it. Good luck!',
    '<button type="button" class="ghost">Einführung überspringen</button></div>':
      '<button type="button" class="ghost">Skip tutorial</button></div>'
  },

  /* Stellen, die keine eigene Zeichenkette sind oder deren Zeichenkette
     zu kurz ist, um sie überall zu ersetzen. Jede muss genau einmal
     vorkommen, sonst bricht der Build ab. */
  stellen: [
    ['js/entities.js', ".replace('.', ',')", ''],                        // Dezimalpunkt statt Komma
    ['js/game.js', "t[2] + '.' + t[1] + '.' + t[0]", "t[0] + '-' + t[1] + '-' + t[2]"],   // Datum ISO
    ['js/game.js', "String(d.getDate()).padStart(2, '0') + '.' +\n                  String(d.getMonth() + 1).padStart(2, '0') + '.' + d.getFullYear()", 'heute(d)'],
    ['js/config.js', "name: 'Vorrang',    short: 'V'", "name: 'Vorrang',    short: 'H'"],
    ['js/config.js', "name: 'Sparlast',   short: 'S'", "name: 'Sparlast',   short: 'L'"],
    ['js/config.js', "name: 'Schnellster',  short: 'T'", "name: 'Schnellster',  short: 'F'"],
    ['js/config.js', "short: 'EIN'", "short: 'SUP'"],
    ['js/config.js', "short: 'SPE'", "short: 'STO'"],
    ['js/config.js', "short: 'SCH'", "short: 'SHD'"]
  ],

  /* Zeichenketten mit Großbuchstaben, Umlaut oder Leerzeichen, die trotzdem
     kein Text sind. */
  code: [
    'use strict', 'INPUT', 'SUP', 'STO', 'SHD', 'Enter', 'Space', 'source-over',
    '<span>${r[0]}</span><span>${r[1]}</span>',
    '<span class="num">${i + 1}</span><h3>${c.name}</h3><p>${c.desc}</p>',
    ' class="', '</b><span>', '</span></div>', ' class="neu"',
    '<td class="platz">', '<td class="wer">', '<td class="wann">', '<td class="teile">',
    '<input id="ovName" maxlength="', 'CORE DEFENSE · '
  ],

  /* Die Spielseite. Jedes Paar muss genau einmal vorkommen. */
  html: [
    ['<html lang="de">', '<html lang="en">'],
    ['Tower Defense von innen nach außen: Die Wellen kommen von außen, der Strom aus der Mitte.',
     'Tower defense turned inside out: the waves come from outside, the power from the center.'],
    ['<span class="label">Materie</span>', '<span class="label">Matter</span>'],
    ['<span class="label">Energie <b', '<span class="label">Energy <b'],
    ['<span class="label">Kern <b', '<span class="label">Core <b'],
    ['<span class="label">Welle</span>', '<span class="label">Wave</span>'],
    ['>Bauphase<', '>Build phase<'],
    ['Welle starten <small>(Leertaste)</small>', 'Start wave <small>(Space)</small>'],
    ['title="Ton (M)"', 'title="Sound (M)"'],
    ['Eine Hälfte des Feldes auf die andere spiegeln — Grundriss auf Stufe 1, zum normalen Preis  (Taste B)',
     'Mirror one half of the field onto the other — layout at level 1, at normal price  (key B)'],
    ['<span class="pn">Bauplan</span>', '<span class="pn">Blueprint</span>'],
    ['Welle <b id="draftWave">0</b> gehalten', 'Wave <b id="draftWave">0</b> held'],
    ['Eine Verbesserung für den Rest der Partie', 'One upgrade for the rest of the run'],
    ['Bau auf ein freies Feld umsetzen — Stufe und Einstellungen bleiben  (Taste V)',
     'Move the building to a free tile — level and settings are kept  (key V)'],
    ['>Neu starten<', '>Restart<'],
    ['>Neu anfangen<', '>Start over<']
  ]
};
